import { ResiduoCategoria, DeviceConfig, TipoResiduoId } from '../types';

export const APP_VERSION = '1.0.0';

export const RESIDUO_CATEGORIAS: ResiduoCategoria[] = [
  {
    id: 'COMUM',
    nome: 'COMUM',
    subtitulo: 'Resíduos não recicláveis e não contaminados',
    grupoAnvisa: 'Grupo D',
    corHex: '#475569',
    bgClass: 'hover:border-slate-400 bg-slate-50/70 dark:bg-slate-900/60',
    borderClass: 'border-slate-300 dark:border-slate-700',
    textClass: 'text-slate-800 dark:text-slate-200',
    badgeBgClass: 'bg-slate-200 text-slate-800 dark:bg-slate-800 dark:text-slate-200',
    icone: 'Trash2',
    ordem: 1,
  },
  {
    id: 'MIX',
    nome: 'MIX',
    subtitulo: 'Materiais recicláveis secos misturados',
    grupoAnvisa: 'Reciclável',
    corHex: '#0284c7',
    bgClass: 'hover:border-sky-400 bg-sky-50/70 dark:bg-sky-950/40',
    borderClass: 'border-sky-300 dark:border-sky-800',
    textClass: 'text-sky-900 dark:text-sky-200',
    badgeBgClass: 'bg-sky-100 text-sky-800 dark:bg-sky-900/60 dark:text-sky-200',
    icone: 'Recycle',
    ordem: 2,
  },
  {
    id: 'COMPOSTAGEM',
    nome: 'COMPOSTAGEM',
    subtitulo: 'Restos de alimentos e matéria orgânica',
    grupoAnvisa: 'Grupo D',
    corHex: '#15803d',
    bgClass: 'hover:border-emerald-400 bg-emerald-50/70 dark:bg-emerald-950/40',
    borderClass: 'border-emerald-300 dark:border-emerald-800',
    textClass: 'text-emerald-900 dark:text-emerald-200',
    badgeBgClass: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/60 dark:text-emerald-200',
    icone: 'Sprout',
    ordem: 3,
  },
  {
    id: 'QUIMICO',
    nome: 'QUÍMICO',
    subtitulo: 'Medicamentos, reagentes e substâncias químicas',
    grupoAnvisa: 'Grupo B',
    corHex: '#ea580c',
    bgClass: 'hover:border-orange-400 bg-orange-50/70 dark:bg-orange-950/40',
    borderClass: 'border-orange-300 dark:border-orange-800',
    textClass: 'text-orange-900 dark:text-orange-200',
    badgeBgClass: 'bg-orange-100 text-orange-800 dark:bg-orange-900/60 dark:text-orange-200',
    icone: 'FlaskConical',
    ordem: 4,
  },
  {
    id: 'INFECTANTE',
    nome: 'INFECTANTE',
    subtitulo: 'Gaze, curativos, secreções e biológicos',
    grupoAnvisa: 'Grupo A',
    corHex: '#dc2626',
    bgClass: 'hover:border-rose-400 bg-rose-50/70 dark:bg-rose-950/40',
    borderClass: 'border-rose-300 dark:border-rose-800',
    textClass: 'text-rose-900 dark:text-rose-200',
    badgeBgClass: 'bg-rose-100 text-rose-800 dark:bg-rose-900/60 dark:text-rose-200',
    icone: 'Biohazard',
    ordem: 5,
  },
  {
    id: 'PERFUROCORTANTE',
    nome: 'PERFUROCORTANTE',
    subtitulo: 'Agulhas, lâminas, escalpes e vidrarias',
    grupoAnvisa: 'Grupo E',
    corHex: '#ca8a04',
    bgClass: 'hover:border-yellow-400 bg-yellow-50/70 dark:bg-yellow-950/40',
    borderClass: 'border-yellow-300 dark:border-yellow-800',
    textClass: 'text-yellow-900 dark:text-yellow-200',
    badgeBgClass: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/60 dark:text-yellow-200',
    icone: 'Syringe',
    ordem: 6,
  },
  {
    id: 'CNPH',
    nome: 'CNPH - LOGÍSTICA REVERSA',
    subtitulo: 'Centros e produtos homologados reversos',
    grupoAnvisa: 'Especial',
    corHex: '#7c3aed',
    bgClass: 'hover:border-purple-400 bg-purple-50/70 dark:bg-purple-950/40',
    borderClass: 'border-purple-300 dark:border-purple-800',
    textClass: 'text-purple-900 dark:text-purple-200',
    badgeBgClass: 'bg-purple-100 text-purple-800 dark:bg-purple-900/60 dark:text-purple-200',
    icone: 'Boxes',
    ordem: 7,
  },
  {
    id: 'TAMPINHAS',
    nome: 'TAMPINHAS',
    subtitulo: 'Tampas plásticas para projetos socioambientais',
    grupoAnvisa: 'Reciclável',
    corHex: '#0d9488',
    bgClass: 'hover:border-teal-400 bg-teal-50/70 dark:bg-teal-950/40',
    borderClass: 'border-teal-300 dark:border-teal-800',
    textClass: 'text-teal-900 dark:text-teal-200',
    badgeBgClass: 'bg-teal-100 text-teal-800 dark:bg-teal-900/60 dark:text-teal-200',
    icone: 'Disc',
    ordem: 8,
  },
  {
    id: 'PECAS_ANATOMICAS',
    nome: 'PEÇAS ANATÔMICAS',
    subtitulo: 'Tecidos, membros e material biológico especial',
    grupoAnvisa: 'Grupo A',
    corHex: '#991b1b',
    bgClass: 'hover:border-red-500 bg-red-50/70 dark:bg-red-950/40',
    borderClass: 'border-red-300 dark:border-red-800',
    textClass: 'text-red-950 dark:text-red-200',
    badgeBgClass: 'bg-red-100 text-red-900 dark:bg-red-900/60 dark:text-red-200',
    icone: 'Activity',
    ordem: 9,
  },
  {
    id: 'SUCATA_ELETRONICA',
    nome: 'SUCATA ELETRÔNICA',
    subtitulo: 'Cabos, placas, equipamentos e baterias',
    grupoAnvisa: 'Especial',
    corHex: '#0891b2',
    bgClass: 'hover:border-cyan-400 bg-cyan-50/70 dark:bg-cyan-950/40',
    borderClass: 'border-cyan-300 dark:border-cyan-800',
    textClass: 'text-cyan-900 dark:text-cyan-200',
    badgeBgClass: 'bg-cyan-100 text-cyan-800 dark:bg-cyan-900/60 dark:text-cyan-200',
    icone: 'Cpu',
    ordem: 10,
  },
];

export const RESIDUO_MAP: Record<TipoResiduoId, ResiduoCategoria> = RESIDUO_CATEGORIAS.reduce(
  (acc, cur) => {
    acc[cur.id] = cur;
    return acc;
  },
  {} as Record<TipoResiduoId, ResiduoCategoria>
);

export const DEFAULT_CONFIG: DeviceConfig = {
  device_id: 'HAOC-TAB-01',
  device_name: 'Tablet Pesagem 01',
  location: 'Área Central de Resíduos - Subsolo 1',
  hospital_name: 'Hospital Alemão Oswaldo Cruz',
  unidade_hospitalar: 'Unidade Paulista',
  default_operator: 'Operador de Higiene e Meio Ambiente',
  matricula_operador: 'HAOC-8942',
  totem_pin: '1908', // Year HAOC was founded
  totem_mode: false,
  theme: 'light',
  auto_reset_seconds: 3,
  setup_completed: false,
  app_version: APP_VERSION,
};

export const UNIDADES_HOSPITALARES = [
  'Unidade Paulista (Rua Treze de Maio)',
  'Unidade Vergueiro',
  'Unidade Campo Belo',
  'Centro de Especialidades',
  'Centro Médico Alphaville',
];
